name: Build Librera Reader

# Define when the workflow should be triggered
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Set NDK version to 22.1.7171670
 #     ANDROID_NDK_VERSION: "22.1.7171670"
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk
    steps:   
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
       distribution: 'adopt'
       java-version: '17'

 #    - name: Set up Android SDK
   #    uses: android-actions/setup-android@v2
   #    with:
   #     api-level: 30
     #   build-tools: '30.0.3'
    #    ndk: ${{ env.ANDROID_NDK_VERSION }}
    # Cache gradle dependencies
  #   - name: Cache Gradle packages
  #     uses: actions/cache@v2
   #    with:
  #      path: |
   #       ~/.gradle/caches
   #       ~/.gradle/wrapper
    #    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
   #     restore-keys: |
   #       ${{ runner.os }}-gradle-
    - name: Checkout code
      uses: android-actions/setup-android@v3.2.1
     # with:
    # cmdline-tools-version. See https://developer.android.com/studio#command-line-tools-only
    #    cmdline-tools-version: # optional, default is 10406996
    # Android SDK is usable only after the license agreement. Should setup-android agree to the licences, provided by "sdkmanager --licenses"
    #    accept-android-sdk-licenses: # optional, default is true
    # Should accepted licenses be logged. If not, accepted licences will be accepted silently
     #   log-accepted-android-sdk-licenses: # optional, default is true
    # Additional packages to install
     #   packages: # optional, default is tools platform-tools
       
            
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Gradle
      env:
        RELEASE_STORE_FILE: "keystore.pkcs12"
        RELEASE_STORE_PASSWORD: "123456"
        RELEASE_KEY_PASSWORD: "123456"
        RELEASE_KEY_ALIAS: "ALIAS"
        
      run:  |
              sudo apt-get install mesa-common-dev libxcursor-dev libxrandr-dev libxinerama-dev libglu1-mesa-dev libxi-dev pkg-config libgl-dev
              sudo keytool -genkey -v -storetype PKCS12 -keystore /keystore.pkcs12 -alias ALIAS -keyalg RSA -keysize 2048 -validity 10000 \
              -storepass android -keypass android -dname "CN=Example, OU=Dev, O=MyCompany, L=City, ST=State, C=US"
              cd Builder
              ./link_to_mupdf_1.24.6.sh
              cd ..
              ./gradlew assembleFdroid


    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
          name: build-artifact
          path: /home/runner/work/LibreraReader/LibreraReader/app/build/outputs/apk/fdroid/debug/Librera/Fdroid-8.9.179-arm64.apk
