name: Build Librera Reader

# Define when the workflow should be triggered
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  build:
    runs-on: ubuntu-latest

    # Cache gradle dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Gradle
        run: 
              cd Builder
              ./link_to_mupdf_1.24.6.sh
              cd ..
              ./gradlew assembleFdroid


      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: app/build/outputs
